pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    // 🚀 FIX CHÍ MẠNG: Khai báo tập trung phiên bản Android Build Tools tương thích Gradle 9.x
    plugins {
        id 'com.android.application' version '8.2.2'
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://api.涼風.tw/maven' }
    }
}
rootProject.name = "VCamModule"
include ':app'
