pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    // Ép hệ thống phân giải thư viện độc lập, không cho các task tự ý thay đổi cấu trúc ngầm
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "VCamModule"
include ':app'
